[package]
name = "shellbe-plugin-sdk"
version = "2.0.0"
edition = "2021"
authors = ["Arash"]
description = "SDK for developing plugins for ShellBe"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
thiserror = "1.0"